FROM node:alpine as build
WORKDIR /app
COPY package.json .
RUN  npm cache clean --force --unsafe-perm && npm install

COPY . .

RUN npm run build

FROM nginx:latest
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 8088