
#FROM node:lts-alpine
#WORKDIR "/app"
#COPY ./package.json ./
#RUN npm install
#RUN npm install pm2 -g
#COPY . .
#CMD ["pm2-runtime", "ecosystem.config.js"]
#EXPOSE 8088

FROM node:lts-alpine
WORKDIR "/app"
COPY ./package.json ./
RUN npm install
RUN npm install pm2 -g
COPY . .
EXPOSE 8088
CMD ["npm", "run",  "prod"]
